# Generated by Django 5.1.1 on 2024-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationtype",
            name="location_type",
            field=models.CharField(
                help_text="Zadejte název typu mokřadu, například: rybník, tůň, stoka",
                max_length=100,
                unique=True,
                verbose_name="Typ lokality",
            ),
        ),
    ]
