# Generated by Django 5.1.1 on 2024-10-07 11:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0002_alter_locationtype_location_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        help_text="Rok, kdy byla lokalita zaznamenána",
                        verbose_name="Rok",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název lokality",
                        max_length=200,
                        verbose_name="Název lokality",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Zadejte souřadnice lokality",
                        null=True,
                        srid=4326,
                        verbose_name="Bod",
                    ),
                ),
                (
                    "location_type",
                    models.ForeignKey(
                        help_text="Vyberte typ lokality",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbolovo.locationtype",
                        verbose_name="Typ lokality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokalita",
                "verbose_name_plural": "Lokality",
                "ordering": ["name", "year"],
            },
        ),
    ]
