# Generated by Django 5.1.1 on 2024-10-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        help_text="Zadejte název typu mokřadu, například: rybník, tůň, stoka",
                        max_length=100,
                        verbose_name="Typ lokality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ lokality",
                "verbose_name_plural": "Typy lokalit",
                "ordering": ["location_type"],
            },
        ),
    ]
