# Generated by Django 5.1.1 on 2024-10-07 11:16

import dbolovo.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0003_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="year",
            field=dbolovo.fields.SpecialYearField(
                help_text="Rok, kdy byla lokalita zaznamenána", verbose_name="Rok"
            ),
        ),
    ]
