# Generated by Django 5.1.1 on 2024-10-07 11:21

import dbolovo.fields
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0004_alter_location_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    dbolovo.fields.SpecialYearField(
                        help_text="Rok, kdy byl vzorek odebrán", verbose_name="Rok"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název vzorku",
                        max_length=200,
                        verbose_name="Název vzorku",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Zadejte souřadnice odběru vzorku",
                        null=True,
                        srid=4326,
                        verbose_name="Bod",
                    ),
                ),
                (
                    "location_type",
                    models.ForeignKey(
                        help_text="Vyberte typ lokality, ze které byl vzorek odebrán",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbolovo.locationtype",
                        verbose_name="Typ lokality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vzorek",
                "verbose_name_plural": "Vzorky",
                "ordering": ["name", "year"],
            },
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
