# Generated by Django 5.1.1 on 2024-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0007_rename_sample_collectedsample"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectedsample",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Zadejte jedinečný identifikátor vzorku",
                max_length=100,
                verbose_name="Identifikátor vzorku",
            ),
        ),
    ]
