# Generated by Django 5.1.4 on 2025-11-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0010_alter_samplemeasurement_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplemeasurement",
            name="sample",
        ),
        migrations.RemoveField(
            model_name="samplemeasurement",
            name="parameter",
        ),
        migrations.RemoveField(
            model_name="samplemeasurement",
            name="unit",
        ),
        migrations.DeleteModel(
            name="CollectedSample",
        ),
        migrations.DeleteModel(
            name="SampleMeasurement",
        ),
    ]
