# Generated by Django 5.1.4 on 2025-11-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0011_remove_samplemeasurement_sample_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Parameter",
        ),
        migrations.DeleteModel(
            name="Unit",
        ),
    ]
