# Generated by Django 5.1.4 on 2025-11-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0012_delete_parameter_delete_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název měřeného parametru, například pH nebo obsah těžkých kovů",
                        max_length=100,
                        unique=True,
                        verbose_name="Název parametru",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Zadejte jednotku měření, například mg/l nebo pH",
                        max_length=50,
                        unique=True,
                        verbose_name="Jednotka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametr",
                "verbose_name_plural": "Parametry",
                "ordering": ["name"],
                "unique_together": {("name", "unit")},
            },
        ),
    ]
