# Generated by Django 5.1.4 on 2025-11-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0013_parameter"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="parameter",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="parameter",
            name="name",
            field=models.CharField(
                help_text="Zadejte název měřeného parametru, například pH nebo obsah těžkých kovů",
                max_length=100,
                verbose_name="Název parametru",
            ),
        ),
        migrations.AddConstraint(
            model_name="parameter",
            constraint=models.UniqueConstraint(
                fields=("name", "unit"), name="unique_parameter_unit"
            ),
        ),
    ]
