# Generated by Django 5.1.4 on 2025-11-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dbolovo",
            "0014_alter_parameter_unique_together_alter_parameter_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="unit",
            field=models.CharField(
                help_text="Zadejte jednotku měření, například mg/l nebo pH",
                max_length=50,
                verbose_name="Jednotka",
            ),
        ),
    ]
