# Generated by Django 5.1.4 on 2025-11-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0015_alter_parameter_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationtype",
            options={
                "ordering": ["name"],
                "verbose_name": "Typ lokality",
                "verbose_name_plural": "Typy lokalit",
            },
        ),
        migrations.RenameField(
            model_name="locationtype",
            old_name="location_type",
            new_name="name",
        ),
    ]
