# Generated by Django 5.1.4 on 2025-11-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0016_alter_locationtype_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LocationType",
        ),
    ]
