# Generated by Django 5.1.4 on 2025-11-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0017_delete_locationtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název typu mokřadu, například: rybník, tok, zemědělská půda",
                        max_length=100,
                        unique=True,
                        verbose_name="Typ lokality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ lokality",
                "verbose_name_plural": "Typy lokalit",
                "ordering": ["name"],
            },
        ),
    ]
