# Generated by Django 5.1.4 on 2025-11-03 09:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0018_locationtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte název konkrétní lokality, například: Rybník Hluboký",
                        max_length=200,
                        unique=True,
                        verbose_name="Název lokality",
                    ),
                ),
                (
                    "gps",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Zadejte souřadnice lokality (ve formátu WGS84)",
                        srid=4326,
                        verbose_name="GPS souřadnice",
                    ),
                ),
                (
                    "location_type",
                    models.ForeignKey(
                        help_text="Vyberte typ této lokality, např. rybník, tůň nebo stoka",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="dbolovo.locationtype",
                        verbose_name="Typ lokality",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lokalita",
                "verbose_name_plural": "Lokality",
                "ordering": ["name"],
            },
        ),
    ]
