# Generated by Django 5.2.7 on 2025-11-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0019_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.ForeignKey(
                help_text="Vyberte typ této lokality, např. rybník, tůň nebo stoka",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="locations",
                to="dbolovo.locationtype",
                verbose_name="Typ lokality",
            ),
        ),
    ]
