# Generated by Django 5.2.7 on 2025-11-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0020_alter_location_location_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Zadejte jednotku měření, například mg/l nebo pH",
                        max_length=50,
                        unique=True,
                        verbose_name="Jednotka",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jednotka",
                "verbose_name_plural": "Jednotky",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="parameter",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dbolovo.unit"
            ),
        ),
    ]
