# Generated by Django 5.2.7 on 2025-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0021_unit_alter_parameter_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
