# Generated by Django 5.2.7 on 2025-11-04 10:14

import dbolovo.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0022_unit_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", dbolovo.fields.SpecialYearField()),
                ("original_name", models.CharField(max_length=100)),
                (
                    "sample_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField()),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dbolovo.location",
                    ),
                ),
            ],
        ),
    ]
