# Generated by Django 5.2.8 on 2025-11-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0023_sample"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"ordering": ["year", "location"]},
        ),
        migrations.AlterUniqueTogether(
            name="sample",
            unique_together={("year", "location", "sample_number")},
        ),
    ]
