# Generated by Django 5.2.7 on 2025-12-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dbolovo", "0025_measure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={"verbose_name": "Měření", "verbose_name_plural": "Měření"},
        ),
        migrations.AlterModelOptions(
            name="sample",
            options={
                "ordering": ["year", "location"],
                "verbose_name": "Vzorek",
                "verbose_name_plural": "Vzorky",
            },
        ),
    ]
